# vim:set ft=dockerfile:

# Docs generation Dockerfile

FROM python:3-alpine

LABEL MAINTAINER="Paolo Casciello <paolo.casciello@scalebox.it>"

RUN mkdir /workspace
WORKDIR /workspace/docs

RUN pip install -U pip
RUN pip install -U sphinx sphinx-autobuild

CMD sphinx-autobuild --host 0.0.0.0 --port 9999 . _build/html
